controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - kuka_iiwa_joint_1
        - kuka_iiwa_joint_2
        - kuka_iiwa_joint_3
        - kuka_iiwa_joint_4
        - kuka_iiwa_joint_5
        - kuka_iiwa_joint_6
        - kuka_iiwa_joint_7
      constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.02
        kuka_iiwa_joint_1: {trajectory: 0.1, goal: 0.1}
        kuka_iiwa_joint_2: {trajectory: 0.1, goal: 0.1}
        kuka_iiwa_joint_3: {trajectory: 0.1, goal: 0.1}
        kuka_iiwa_joint_4: {trajectory: 0.1, goal: 0.1}
        kuka_iiwa_joint_5: {trajectory: 0.1, goal: 0.1}
        kuka_iiwa_joint_6: {trajectory: 0.1, goal: 0.1}
        kuka_iiwa_joint_7: {trajectory: 0.1, goal: 0.1}
      state_publish_rate: 50
      action_monitor_rate: 20
